# 
# sigma: if the distance from a determined deploy position to the current position is lesser than sigma, then _push_robot won't make a push and will mark the robot as obstacl1
#

sim_001:
  map:
     "boundary"   : [[0, 0], [10, 12]]
     "obstacles"  : []
     "entrypoint" : [1, 1]
  robot_radius: 1.414213562
  sigma: 0.2
  beta: 0.02

sim_002:
  map:
     "boundary"   : [[0, 0], [10, 12]]
     "obstacles"  : [[[1,6],[3,8]],[[4, 4], [6, 6]], [[7, 8], [9, 11]]]
     "entrypoint" : [1, 1]
  robot_radius: 1.414213562
  sigma: 0.2
  beta: 0.02

sim_003:
  map:
     "boundary"   : [[0, 0], [10, 12]]
     "obstacles"  : [[[7,0], [8,10]], [[0,7], [4,8]]]
     "entrypoint" : [1, 1]
  robot_radius: 1.414213562
  sigma: 0.2
  beta: 0.02

sim_004:
  map:
     "boundary"   : [[0, 0], [10, 12]]
     "obstacles"  : [[[3,0], [4,6]], [[8,0], [9,7]]]
     "entrypoint" : [1, 1]
  robot_radius: 1.414213562
  sigma: 0.2
  beta: 0.02